---
title: "Untitled"
author: "TC"
date: "10/30/2019"
output: 
  html_notebook:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path="test112_notebook_figs/")
```

## R Markdown

https://stackoverflow.com/questions/58600399/how-do-you-run-an-r-file-on-ubuntu?noredirect=1#comment103544013_58600399

```{r pressure, echo=FALSE}
plot(pressure)
```

```{r pressure2, echo=FALSE}
plot(pressure)
```

```{r}
library(lubridate)

get_series = function(start, duration){
  start= lubridate::as_datetime(start, format="%m-%d")
  end = start + days(duration-1)
  if(start<=end){
    return(seq(start, end, by="1 day"))
  }
  else{
    return(NULL)
  }
  
}

Date <- c("06-01","06-02","06-03","06-04","06-04")
Last_day <- c(4,3,1,1,0)
Data1 <- data.frame(Date,Last_day, stringsAsFactors=FALSE)

rslt = lapply(1:nrow(Data1), function(i){
  rslt = get_series(Data1$Date[i], Data1$Last_day[i])
  rslt=as.character(rslt)
  return(rslt)
})

table(unlist(rslt))
```


```{r echo=FALSE}
# 构建数据：
date_df <- data.frame(start = c("06-01","06-02","06-03","06-04","06-04"), 
                      duration = c(4,3,1,1,0))
# 识别日期：
date_df$ystart <- as.Date(paste0('2019-', date_df$start))
# 生成所有日期：
date_ls <- mapply(function(x1, x2) format(seq(from = x1, length.out = x2, by = 1), '%m-%d'), 
                  date_df$ystart, date_df$duration)
# 统计频次：
table(unlist(date_ls))
```