---
title: "Untitled"
author: "tc"
date: "February 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(stringr)
library(rlang)

tbl_sample <- read_csv(file = "./sample.csv") 
```

```{r}
var_sr <- tbl_sample %>% 
  select(ends_with("_sr")) %>%
  select(- app_date_sr) %>% 
  names(.)

var_sc <- var_sr %>% 
  str_sub(start = 1L, end = (str_length(.) - 3)) %>% 
  paste0(., "Sc")

fun_count <- function(df, group_var1, group_var2, group_var3 = app_date_sr) {
  group_var1 <- enquo(group_var1)
  group_var2 <- enquo(group_var2)
  group_var3 <- enquo(group_var3)
  
  print(group_var1)

  df %>% select(id
                ,!!group_var1
                ,!!group_var2
                ,!!group_var3) %>% 
    group_by(!!group_var1
             ,!!group_var2
             ,!!group_var3) %>% 
    summarise(n = n()) %>% 
    spread(!!group_var3, n)
}
```


```{r}
tbl_fun_test <- fun_count(df = tbl_sample, group_var1 = age_sr, group_var2 = ageSc) #与预期结果相符

# output <- vector("list", length(var_sr)) #与预期结果不符
# for (i in 1:3) {
#   output[[i]] <-
#     fun_count(df = tbl_sample,
#               group_var1 = var_sr[[i]],
#               group_var2 = var_sc[[i]])
# }

tbl_fun_test
```


```{r}

dummy <- function() {
  output <- vector("list", length(var_sr)) #与预期结果不符
  for (i in 1:3) {
    tmp1 = (var_sr[[i]])
    tmp2 = (var_sc[[i]])
    message(tmp1," ", tmp2)
    output[[i]] <-
      fun_count(df = tbl_sample,
                group_var1 = tmp1,
                group_var2 = tmp2)
  }
  
  return(output)
}

output2 <- dummy()

output2[[1]]
```



```{r}
test <- expand.grid(rnorm(100),rnorm(100))
```

```{r}
var <- quote(mpg)
dplyr::select(mtcars, !! var)
```




```{r}

df1 <- tibble(x = 1:3)

df2 <- tibble(x = 1:3,a = 1:3)

df3 <- tibble(x = 1:3, a= 4:6)

df4 <- tibble(x = 1:3, a =7:9)
a = 10
mutate(df1, y = a + x)
mutate(df2, y = a + x)
mutate(df3, y = a + x)
mutate(df4, y = a + x)
```

