---
title: "test48"
author: "TC"
date: "July 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(nycflights13)
library(tidyverse)
library(lubridate)
library(modelr)
## DATA USED

daily <- flights %>% 
  mutate(date = make_date(year, month, day)) %>% 
  group_by(date) %>% 
  summarise(n = n()) %>% 
  mutate(wday = lubridate::wday(date, label = T))

mod_daily <- MASS::rlm(n ~ wday * splines::ns(date, 5), data = daily)

daily <- daily %>% 
  add_predictions(mod_daily) %>% 
  add_residuals(mod_daily)

## TOP_N TRY

daily %>% 
  group_by() %>%
  top_n(4, wt=n)

# SOLUTION USING ORDER()

daily[order(-daily$resid),] %>% 
      head()
```



```{r}
timeperiod <- 1:18
ID <- c("TOM", "TOM", "SALLY", "SALLY", "RICHIE", "TOM", "TOM", "SALLY", "RICHIE", "RICHIE", "RICHIE", "SALLY", "TOM", "TOM", "TOM", "RICHIE", "RICHIE", "RICHIE")
referredvisit <- c(0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0)
# df <- cbind(timeperiod, ID, referredvisit)
# df <- as.data.frame(df)

result <- c(0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 1, 0, 2, 0)

df <- data.frame(timeperiod,ID,referredvisit,result)
```

```{r}

library(tidyverse)

df %>% group_by(ID) %>% arrange(timeperiod, .by_group = TRUE) -> df.tmp



```

```{r}
df.tmp

result2 = numeric(nrow(df.tmp))

lastid = ""

count = 0

for (i in 1:nrow(df.tmp)){
  if (lastid != df.tmp$ID[i] ){
    count = 0;
    lastid = df.tmp$ID[i]
  }
  if (df.tmp$referredvisit[i] == 1){
    count = count +1
    result2[i] == 0
  }
  
  if (df.tmp$referredvisit[i] ==0) {
    result2[i] = count
    count = 0
    
  }
}

df.tmp$result2 = result2

```

